fixtures:
  repositories:
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    xtreemfs: "https://github.com/wavesoftware/puppet-xtreemfs.git"
    openssl: "https://github.com/camptocamp/puppet-openssl.git"
    java_ks: "https://github.com/puppetlabs/puppetlabs-java_ks.git"
  symlinks:
    fogstore: "#{source_dir}"
